### ISSUE TITLE
search translation in superclass if it's not in subclass.

### ISSUE THREAD

**Issue by jorgefernando1** [thetron/mongoid-enum#34]
When i have a inherited model and a enum in the superclass, I need to repeat the translation. E.g

``` ruby
class Employee
 enum :foo,  [:bar, :baz, :zaz]

class Manager < Employee
```

and in translation .yml file I need to have

``` yml
enums:
  employee:
    foo:
      bar: BAR
      baz: BAZ
      zaz: ZAZ

  employees/manager:
    foo:
      bar: BAR
      baz: BAZ
      zaz: ZAZ
```

So if I don't have the **employees/manager** defined, its should search in the **employee**
